FROM python:3.9-slim
    
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt && rm requirements.txt

ENV DB_HOST=$(DB_HOST)
ENV DB_USER=$(DB_USER)
ENV DB_PASSWORD=$(DB_PASSWORD)
ENV DB_NAME=$(DB_NAME)

CMD ["sh", "-c", "sleep 5 && python main.py"]
###### слип нужен т.к. почему-то скрипт не ждет пока бд полностью откроется