FROM python:3.9-slim
    
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt && rm requirements.txt

ENV DB_HOST=$(DB_HOST)

ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_DATABASE

ENV DB_USER=$MYSQL_USER
ENV DB_PASSWORD=$MYSQL_PASSWORD
ENV DB_NAME=$MYSQL_DATABASE

CMD ["sh", "-c", "env | grep DB_ && sleep 5 && python main.py"]
###### слип нужен т.к. почему-то скрипт не ждет пока бд полностью откроется