FROM python:3.9-slim

WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt && rm requirements.txt

ENV DB_HOST=127.0.0.1
ENV DB_USER=app
ENV DB_PASSWORD=very_strong
ENV DB_NAME=example

CMD ["sh", "-c", "sleep 5 && python main.py"]
# слип нужен т.к. почему-то скрипт не ждет пока бд полностью откроется